image: thomasschweich/open-portfolio:op-gitpod
ports:
- port: 8000
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
tasks:
    - env:
        PIP_USER: no
        PATH: ${PATH}:${HOME}/.poetry/bin
      before: . ${HOME}/.poetry/env && . /open-portfolio/venv/bin/activate
      command: poetry shell
