image:
  file: Dockerfile
ports:
- port: 8000
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
tasks:
  - before: source ${HOME}/.poetry/env
    command: PIP_USER=no poetry shell
    env:
      PIP_USER: no
