image: thomasschweich/open-portfolio:op-gitpod
ports:
- port: 8000
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
tasks:
    - before: . ${HOME}/.poetry/env && . venv/bin/activate
      command: poetry shell
